config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users

    resources :orders

    resources :line_items

    resources :carts

    get "store/index"

    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/controllers/carts_controller.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
class CartsController < ApplicationController
  #skip_before_action :authorize, only: [:create, :update, :destroy]
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  # ...
  private
  # ...

    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>
<div class="cart_title">Your Cart</div>
<table>
	<%= render(cart.line_items) %>

	<tr class="total_line">
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
	</tr>
</table>

<%= button_to "Checkout", new_order_path, method: :get %>

<%= button_to 'Empty cart', cart, method: :delete, confirm: 'Are you sure?' %>
<% end %>

app/views/carts/_form.html.erb
<div class="depot_form">
  
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %>
          prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <fieldset>
      <legend>Enter User Details</legend>
      <div>
        <%= f.label :name %>:
        <%= f.text_field :name, size: 40 %>
      </div>

      <div>
        <%= f.label :password, 'Password' %>:
        <%= f.password_field :password, size: 40 %>
      </div>

      <div>
        <%= f.label :password_confirmation, 'Confirm' %>:
        <%= f.password_field :password_confirmation, size: 40 %>
      </div>

      <div>
        <%= f.submit %>
      </div>

    </fieldset>
  <% end %>
</div>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing orders</h1>
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>

<table>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', 
      method: :delete %></td>      
    </tr>
  <% end %>

</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<div class="cart_title">Your Cart</div>
<table>
	<%= render (@cart.line_items) %>

	<tr class="total_line">
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
	</tr>
</table>

<%= button_to 'Empty cart', @cart, method: :delete, confirm: 'Are you sure?' %>